### ISSUE TITLE
Get 100% bootstrapping working in Go 1.6

### ISSUE THREAD

**Issue by keroserene** [keroserene/snowflake#22]
After upgrading to 1.6, the client fails to bootstrap, and no offers/answers get exchanged. This is likely related to the underlying go-webrtc code which also needs a 1.6 fix. After setting the `GODEBUG` env var, signaling succeeds, but bootstrapping still fails at:
`Problem bootstrapping. Stuck at 10%: Finishing handshake with directory server. (DONE; DONE; count 1; recommendation warn; host 0000000000000000000000000000000000000000 at 0.0.3.0:1)`

**Comment by arlolra** [comment]
Probably should confirm that it's still working as expect on 1.5, since I've been mucking around in go-webrtc a bit today.

**Comment by arlolra** [comment]
For what it's worth, I'm stuck at 10% even after checking out a known working commit of go-webrtc and using 1.5, so this probably isn't to blame on 1.6

**Comment by keroserene** [comment]
Hmm, that's odd. I can successfully bootstrap to 100% (using latest Snowflake) when I use Go 1.5.
However, when I revert to much older known working commits of Snowflake and use Go 1.6, it also gets stuck at 10%. Maybe it's possible that one was built with 1.6 or the other with 1.5?

**Comment by arlolra** [comment]
Ah, ok, agreed re:1.6. I'm getting the same bootstrapping problem as you above.

But in 1.5, I get ...
```
2016/02/22 18:17:17 Sending offer via BrokerChannel...
Target URL:  https://snowflake-reg.appspot.com/ 
Front URL:   www.google.com
2016/02/22 18:17:17 BrokerChannel Response:
503 Service Unavailable
```

**Comment by arlolra** [comment]
keroserene/go-webrtc#36 is closed now, so this should work.

I'm getting the same thing as on 1.5 though, which I've opened as #26
