### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by arlolra** [keroserene/snowflake#26]
I keep getting,

```
2016/03/09 13:02:10 Sending offer via BrokerChannel...
Target URL:  https://snowflake-reg.appspot.com/ 
Front URL:   www.google.com
2016/03/09 13:02:10 BrokerChannel Response:
503 Service Unavailable
```

will investigate in a bit, unless you know the answer immediately.

**Comment by keroserene** [comment]
This just means the Broker doesn't have any snowflake proxies available to give you.
I tend to just leave a few going in my browser all the time, but my laptop was off just now.

Try it now, it should work.
You can probably also run your own if I'm not around :)
But, thanks for this -- I'll make the error message more informative

**Comment by arlolra** [comment]
> This just means the Broker doesn't have any snowflake proxies available to give you.

Aha!

```
Mar 09 14:13:46.000 [notice] Tor has successfully opened a circuit. Looks like client functionality is working.
Mar 09 14:13:46.000 [notice] Bootstrapped 100%: Done
^CMar 09 14:13:52.000 [notice] Interrupt: exiting cleanly.
λ (master) go version
go version go1.6 darwin/amd64
```

> I'll make the error message more informative

Great, I'll leave this open as a reminder (or maybe fix it myself :)

**Comment by keroserene** [comment]
Took care of it :)

**Comment by arlolra** [comment]
ty ty
