### ISSUE TITLE
I want to learn moar

### ISSUE THREAD

**Issue by jart** [keroserene/snowflake#28]
I hope you're having fun with WebRTC. Telephony engineering is basically the most complicated thing imaginable. It's governed by a plethora of crazy RFCs.

Because WebRTC is so complicated, I'm having trouble groking this project. Is thine intention to make Tor traffic appear as though it were WebRTC traffic when viewed over the wire?

If so, do you have a design doc? If not, please consider writing one. I would be happy to take a look. I have extensive experience with Go, WebRTC, App Engine, and CoffeeScript.

**Comment by keroserene** [comment]
> Because WebRTC is so complicated, I'm having trouble groking this project. Is thine intention to make Tor traffic appear as though it were WebRTC traffic when viewed over the wire?

Not quite. It's a pluggable transport meant to vastly increase the number of users who can easily connect, despite being in a filtered zone, using a large number of ephemeral in-browser volunteer "snowflake" bridges and some of the advantages of WebRTC (primarily ICE negotiation). See here for some basic info: https://lists.torproject.org/pipermail/tor-dev/2016-January/010310.html

There is a design doc. I might detail some "how it works" stuff in the README later. Thanks.
If you're actually interested, you're probably better off familiarizing with [flashproxy](https://crypto.stanford.edu/flashproxy/) first.
