### ISSUE TITLE
Prefer HTTPS for snowflake website and embed

### ISSUE THREAD

**Issue by teor2345** [keroserene/snowflake#40]
It's not really safe to load the snowflake proxy JavaScript over HTTP.

But the page:
https://keroserene.net/snowflake/
recommends a HTTP embed.

And when I go to:
http://keroserene.net/snowflake/options.html
http://keroserene.net/snowflake/embed.html
They could redirect to the HTTPS versions, but don't.
For the embed page, is this because the redirect could break the iframe?

**Comment by arlolra** [comment]
This is just a relic of the fact that we only recently deployed wss for proxy-to-server communication.  

See https://trac.torproject.org/projects/tor/ticket/18654

**Comment by keroserene** [comment]
Thanks for pinging about this  :+1: 
Had been intending to do this minor update. The wss relay is now default in the proxy, and HTTPS embed should be working
