### ISSUE TITLE
problem with go get

### ISSUE THREAD

**Issue by arminkz** [keroserene/snowflake#44]
hello,
thank you guys! snowflakes is just an amazing idea. i was trying to run the client but im getting this error when running `go get` :

`# github.com/pion/webrtc
../../src/github.com/pion/webrtc/dtlstransport.go:257:4: cannot use cert.x509Cert (type *x509.Certificate) as type tls.Certificate in field value
../../src/github.com/pion/webrtc/dtlstransport.go:258:4: unknown field 'PrivateKey' in struct literal of type dtls.Config
../../src/github.com/pion/webrtc/dtlstransport.go:300:34: remoteCert.Raw undefined (type [][]byte has no field or method Raw)
../../src/github.com/pion/webrtc/dtlstransport.go:301:29: cannot use remoteCert (type [][]byte) as type *x509.Certificate in argument to t.validateFingerPrint`

btw, im using macOS 10.14.6 and i installed `go` via `brew`

**Comment by arlolra** [comment]
Which version of `go`?  Maybe try updating all your packages with `go get -u all`.

**Comment by arminkz** [comment]
updating solved the problem.

thanks :)
