### ISSUE TITLE
initial WebRTC + websocket browser snowflake

### ISSUE THREAD

**Issue by keroserene** [keroserene/snowflake#5]
Try to mash the go-webrtc chat demo and flashproxy badge code to allow copy-paste signaling to establish a client-relay pair using WebRTC from client-to-browser and websocket from browser-to-relay.

**Comment by keroserene** [comment]
Have successfully bootstrapped the go webrtc client through the in-browser snowflake to a websocket relay, and was able to browse websites over Tor. I think that qualifies as "initial" as well :)

**Comment by arlolra** [comment]
Nice!
