### ISSUE TITLE
Register proxies with the broker

### ISSUE THREAD

**Issue by arlolra** [keroserene/snowflake#9]
Get the browser snowflakes to register with the broker, and be able to generate an answers on demand.

Who did we decide is going to hold the connection open waiting for the other side? Client or proxy? (Should look that up.)

**Comment by keroserene** [comment]
Currently, the client holds the connection open, waiting for some proxy to obtain the offer and respond with the answer.
It works, but I'm not convinced it's definitely the way :)

**Comment by arlolra** [comment]
Oh, you've got this done. Well then ...
